$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
ignorePaths:
  - .git
  - bun.lockb
  - ./branch_out
  - .changeset
  - drizzle
  - "**/*.svg"
  - .vscode
  - "**/migrations"
  - "**/schema.prisma"
  - "**/analyze"
  - "**/.next"
  - "**/tsconfig.build.tsbuildinfo"
words:
  - Activedescendant
  - acst
  - Anson
  - Autofocus
  - autodocs
  - autoplay
  - awst
  - aest
  - akst
  - astro
  - astrojs
  - Autofocus
  - awst
  - Beamer
  - biomejs
  - Binni
  - bitnami
  - branchname
  - bunx
  - Byrom
  - bvaughn
  - callees
  - catppuccin
  - classname
  - clsx
  - cjsx
  - cmdk
  - Colm
  - commitlint
  - commitlintrc
  - compat
  - consts
  - codespace
  - codespaces
  - crossorigin
  - ctsx
  - datasource
  - datetime
  - dbaeumer
  - degit
  - dotenv
  - dsznajder
  - Duarte
  - Ebene
  - Embla
  - esbenp
  - Focusable
  - hookform
  - ixahmedxi
  - jiti
  - jscoverage
  - jspm
  - kohler
  - lockb
  - lucide
  - Malyavko
  - microbundle
  - mikestead
  - minimise
  - Mintlify
  - mjsx
  - monorepoing
  - mtsx
  - neonctl
  - neondatabase
  - nextjs
  - Noninteractive
  - nuxt
  - nzst
  - onwarn
  - optimisations
  - orbitkit
  - Ornella
  - packagejson
  - pacocoursey
  - pageview
  - peduarte
  - pids
  - Preact
  - posthog
  - quickstart
  - Ratelimit
  - rarr
  - shadcn
  - shiki
  - sonner
  - sslmode
  - starterkit
  - starterkits
  - stylelint
  - stylelintcache
  - stylesheet
  - superjson
  - Tabindex
  - tada
  - tailwindcss
  - tamasfe
  - tanstack
  - thollander
  - todos
  - topbar
  - transpiles
  - treeshake
  - trivago
  - trpc
  - tsbuildinfo
  - tsconfigs
  - tsup
  - Tuite
  - turborepo
  - typecheck
  - typesafe
  - typeof
  - unifiedjs
  - unkey
  - uploadthing
  - vaul
  - Vercel
  - viewports
  - vuepress
  - WITA
  - wscript
  - yoav
  - zustand
