import { Icons } from "@/components/icons"

export const langs = {
  ANGULAR: {
    id: "angular-ts",
    name: "Angular",
    icon: Icons.angular,
    extension: "angular",
  },
  // ASTRO: { id: "astro", name: "Astro", icon: Icons.astro, extension: "" },
  CSS: { id: "css", name: "CSS", icon: Icons.css, extension: "css" },
  // HTML: { id: "html", name: "HTML", icon: Icons.html, extension: "" },
  // JAVA: { id: "java", name: "Java", icon: Icons.java, extension: "" },
  JAVASCRIPT: {
    id: "javascript",
    name: "JavaScript",
    icon: Icons.javascript,
    extension: "js",
  },
  JSON: { id: "json", name: "JSON", icon: Icons.json, extension: "json" },
  // JSX: { id: "jsx", name: "JSX", icon: Icons.jsx, extension: "" },
  // MARKDOWN: { id: "markdown", name: "Markdown", icon: Icons.markdown, extension: "" },
  // MDX: { id: "mdx", name: "MDX", icon: Icons.mdx, extension: "" },
  // PHP: { id: "php", name: "PHP", icon: Icons.php, extension: "" },
  // POSTCSS: { id: "postcss", name: "PostCSS", icon: Icons.postcss, extension: "" },
  // PYTHON: { id: "python", name: "Python", icon: Icons.python, extension: "" },
  // RUBY: { id: "ruby", name: "Ruby", icon: Icons.ruby, extension: "" },
  // SASS: { id: "sass", name: "Sass", icon: Icons.sass, extension: "" },
  // SCSS: { id: "scss", name: "SCSS", icon: Icons.scss, extension: "" },
  SVELTE: {
    id: "svelte",
    name: "Svelte",
    icon: Icons.svelte,
    extension: "svelte",
  },
  // TSX: { id: "tsx", name: "TSX", icon: Icons.tsx, extension: "" },
  TYPESCRIPT: {
    id: "typescript",
    name: "TypeScript",
    icon: Icons.typescript,
    extension: "ts",
  },
  VUE: { id: "vue", name: "Vue", icon: Icons.vue, extension: "vue" },
  // YAML: { id: "yaml", name: "YAML", icon: Icons.yaml, extension: "" },
} as const
